version: '3.4'

services:
  api:
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: ./Dockerfile-dev
    ports:
      - "5005:5005"
    environment:
      FLASK_DEBUG: 1
      FLASK_ENV: docker-development
      FLASK_CONFIG: docker-development
    volumes:
      - ./api:/app
    entrypoint: gunicorn
    command: --bind 0.0.0.0:5005 --access-logfile - wsgi:app --reload
    env_file:
      - './api/.env'
    user: 1000:1000

  frontend:
    restart: unless-stopped
    build:
      context: ./frontend-react
      dockerfile: ./Dockerfile-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-react:/app
    entrypoint: npm run dev
    user: 1000:1000

  mongo:
    image: 'mongo:latest'
    ports:
      - '27019:27017'
    volumes:
      - ./mongo-data:/data/db
    user: 1000:1000

  # postgres:
  #   image: postgres:14.5-alpine
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   logging:
  #     options:
  #       max-size: 10m
  #       max-file: "3"
  #   ports:
  #     - '5433:5432'
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  mongo-data:
  # postgres-data:
