# location: api/app/blueprints

# main
# GET  /
def home(): ...
# GET  /favicon.ico
def favicon(): ...

# api_token_auth  (mongo + sql)
# POST /authorize          @verify_token
def authorize(): ...
# GET  /test_data          @verify_token
def test_data(): ...
# POST /test_post_data     @verify_token
def test_post_data(): ...

# admin  (mongo + sql)
# GET       /              @login_required @admin_required (sql only)
def index(): ...
# GET       /not_authorized
def not_authorized(): ...
# GET, POST /login
def login(): ...
# GET       /logout
def logout(): ...

# settings
# GET  /settings           @verify_token
def settings(): ...
# POST /update_settings    @verify_token
def update_settings(): ...

# subscription
# GET  /details                          @verify_token
def details(): ...
# POST /stripe-customer-portal-session   @verify_token
def stripe_customer_portal_session(): ...
# POST /purchase_lifetime_access         @verify_token
def purchase_lifetime_access(): ...
# POST /change_plan                      @verify_token
def change_plan(): ...
# POST /cancel_plan                      @verify_token
def cancel_plan(): ...

# example
# GET  /feature
def get_feature(): ...
# POST /feature
def create_feature(): ...
# GET  /auth-protected-feature           @verify_token
def get_auth_protected_feature(): ...
# POST /auth-protected-feature           @verify_token
def post_auth_protected_feature(): ...

# error (test_routes)
# GET  /404
def test_404(): ...
# GET  /500
def test_500(): ...
# GET  /error
def error(): ...
