# location: api/app/blueprints

# api/helpers.py
def encode_jwt(data): ...
def decode_jwt(jwt_): ...
def decode_jwt_no_signature_check(jwt_): ...
def build_jwt_url(url, data): ...

# helpers/config.py
def get(config_variable): ...

# email/email.py
def send_async_email(app, msg): ...
def send_email(subject, recipients, sender=None, text_body='', html_body=''): ...

# email/helpers.py
def validate_email(email): ...

# ai/completions.py
def completion_1(question, topic, client): ...

# ai/helpers.py
def calculate_gpt_usage_cost(model, in_tokens, out_tokens, n_calls=1): ...

# error/handlers.py
def internal_server_error(e): ...
def page_not_found(e): ...

# example/services.py
def do_something(data): ...

# example/models.py
class ExampleModel: ...

# payments_stripe/webhooks.py
def get_product_from_checkout_session(session_id): ...

# payments_stripe/security.py
def verify_signature(request): ...

# payments_stripe/helpers.py
def get_or_create_webhook_endpoint(configured_url): ...

# payments_stripe/event_handling.py
class Event: ...

# subscription/helpers.py
def format_timestamp(timestamp, format="%b %-d, %Y"): ...
def subscription_just_renewed(old_end_timestamp, new_start_timestamp): ...
def get_and_convert_status_for_subscription(data, provider="Stripe"): ...
def build_prorations(current_plan, timestamp_end, period="monthly"): ...

# subscription/subscription_plan.py
class SubscriptionPlan: ...  # ABC

# subscription/plan_types.py
class FreeSubscriptionPlan(SubscriptionPlan): ...
class BasicSubscriptionPlan(SubscriptionPlan): ...
class CultivatingSubscriptionPlan(SubscriptionPlan): ...
class LearnedSubscriptionPlan(SubscriptionPlan): ...
class LifetimeSubscriptionPlan(LearnedSubscriptionPlan): ...

# subscription/mixin_mongo.py
class SubscriptionMixin: ...

# subscription/providers/provider.py
class Provider: ...  # ABC

# subscription/providers/stripe.py
class Stripe(Provider): ...

# subscription/providers/solana.py
class Solana(Provider): ...

# subscription/providers/test.py
def generate_random_id(): ...
class TestProvider(Provider): ...

# mongo/api_token_auth/helpers.py
def encode_jwt(data): ...
def decode_jwt(jwt_): ...
def random_string_generator(str_size): ...
def get_user_from_request_headers(headers): ...
def get_user_by_id(id): ...
def get_user_by_email(email): ...
def get_reset_password_url(token): ...
def get_account_deletion_url(token): ...

# mongo/api_token_auth/token_verification.py
def verify_token(func): ...  # decorator

# mongo/api_token_auth/models.py
class BlacklistToken: ...
class User(SubscriptionMixin): ...

# mongo/admin/helpers.py
def get_form_model_attributes(form_model): ...
def get_username(): ...
def get_user_class(user): ...
def random_print_string(): ...

# mongo/admin/route_protection.py
def admin_required(func): ...  # decorator

# mongo/admin/models.py
class Admin: ...

# mongo/models.py
class IPAddress: ...

# sql/api_token_auth/helpers.py
def encode_jwt(data): ...
def decode_jwt(jwt_): ...
def random_string_generator(str_size): ...
def get_user_from_request_headers(headers): ...
def get_user_by_id(id): ...

# sql/api_token_auth/token_verification.py
def verify_token(func): ...  # decorator

# sql/api_token_auth/sql_models.py
class BlacklistToken: ...
class User: ...
class UserSettings: ...
class UserNotifications: ...

# sql/admin/helpers.py
def get_form_model_attributes(form_model): ...
def get_username(): ...
def get_user_class(user): ...
def random_print_string(): ...

# sql/admin/route_protection.py
def admin_required(func): ...  # decorator

# sql/admin/models.py
class Admin: ...

# sql/models.py
class IPAddress: ...

# referral/models.py
class ReferringUser: ...
