# location: api/app/blueprints

# main
# GET  /
def home(): ...
# GET  /favicon.ico
def favicon(): ...

# api_token_auth  (mongo + sql)
# POST /authorize          @verify_token
def authorize(): ...
# GET  /test_data          @verify_token
def test_data(): ...
# POST /test_post_data     @verify_token
def test_post_data(): ...

# admin  (mongo + sql)
# GET       /              @login_required @admin_required (sql only)
def index(): ...
# GET       /not_authorized
def not_authorized(): ...
# GET, POST /login
def login(): ...
# GET       /logout
def logout(): ...

# settings
# GET  /settings           @verify_token
def settings(): ...
# POST /update_settings    @verify_token
def update_settings(): ...

# subscription
# GET  /details                          @verify_token
def details(): ...
# POST /stripe-customer-portal-session   @verify_token
def stripe_customer_portal_session(): ...
# POST /purchase_lifetime_access         @verify_token
def purchase_lifetime_access(): ...
# POST /change_plan                      @verify_token
def change_plan(): ...
# POST /cancel_plan                      @verify_token
def cancel_plan(): ...

# example
# GET  /feature
def get_feature(): ...
# POST /feature
def create_feature(): ...
# GET  /auth-protected-feature           @verify_token
def get_auth_protected_feature(): ...
# POST /auth-protected-feature           @verify_token
def post_auth_protected_feature(): ...

# organizer
# GET  /tasks                        @verify_token
def get_tasks(): ...
# POST /tasks                        @verify_token
def create_task(): ...
# GET  /tasks/<task_id>              @verify_token
def get_task(task_id): ...
# PUT  /tasks/<task_id>              @verify_token
def update_task(task_id): ...
# DELETE /tasks/<task_id>            @verify_token
def delete_task(task_id): ...
# POST /tasks/<task_id>/start        @verify_token
def start_task(task_id): ...
# POST /tasks/<task_id>/stop         @verify_token
def stop_task(task_id): ...
# POST /tasks/<task_id>/snooze       @verify_token
def snooze_task(task_id): ...
# POST /tasks/<task_id>/complete     @verify_token
def complete_task(task_id): ...
# GET  /sessions/active              @verify_token
def get_active_session(): ...
# PUT  /sessions/<session_id>        @verify_token
def update_session(session_id): ...
# GET  /history                      @verify_token
def get_history(): ...
# GET  /schedule                     @verify_token
def get_schedule(): ...
# GET  /capacity                     @verify_token
def get_capacity(): ...
# GET  /stats                        @verify_token
def get_stats(): ...
# GET  /sections                     @verify_token
def get_sections(): ...
# POST /sections                     @verify_token
def create_section(): ...
# PUT  /sections/reorder             @verify_token
def reorder_sections(): ...
# PUT  /sections/<section_id>        @verify_token
def update_section(section_id): ...
# DELETE /sections/<section_id>      @verify_token
def delete_section(section_id): ...

# error (test_routes)
# GET  /404
def test_404(): ...
# GET  /500
def test_500(): ...
# GET  /error
def error(): ...
