"""add groups to users

Revision ID: 164bf7808765
Revises: a4a35662f751
Create Date: 2023-07-21 09:20:43.872124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164bf7808765'
down_revision = 'a4a35662f751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('groups', sa.JSON(), nullable=True, server_default='{}'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('groups')

    # ### end Alembic commands ###
