
FROM python:3.10
COPY ./requirements.txt /app/requirements.txt
WORKDIR /app
RUN apt-get update \
    && apt-get install -y --no-install-recommends
RUN pip install -r requirements.txt
COPY . /app

# EXPOSE 5000
# ENTRYPOINT [ "python3", "app.py" ]
ENTRYPOINT ["gunicorn","--bind","0.0.0.0:5002","-w","1","wsgi:app"]
