name: Backend Production Deploy
on:
  workflow_dispatch:

jobs:

  deploy_backend:
    name: "Deploy to Production"
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: 127.0.0.1
          username: steven
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts

            KEY=$(ssh-keyscan -t rsa github.com)
            if ! grep -q "$KEY" "~/.ssh/known_hosts"; then
              echo "$KEY" >> "~/.ssh/known_hosts"
            fi

            eval $(ssh-agent)
            ssh-add - <<< "${{ secrets.SSH_KEY }}"
            PATH=~/.local/bin:$PATH
            cd ~/life-organizer
            git fetch --all
            git reset --hard origin/master
            ~/life-organizer/api/venv/bin/pip3 install -r ~/life-organizer/api/requirements.txt
            echo ${{ secrets.SUDO_PASSWORD }} | sudo -S systemctl restart life_organizer.service