name: Push To Staging

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy_backend:
    name: "Deploy staging backend"
    runs-on: ubuntu-latest

    # needs: test
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        continue-on-error: false
        with:
          host: %%SERVER_IP%%
          username: steven
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts

            KEY=$(ssh-keyscan -t rsa github.com)
            if ! grep -q "$KEY" ~/.ssh/known_hosts; then
              echo "$KEY" >> ~/.ssh/known_hosts
            fi

            PATH=~/.local/bin:$PATH
            cd ~/%%DIRECTORY_NAME%%-staging
            git fetch --all
            git reset --hard origin/master
            ~/%%DIRECTORY_NAME%%-staging/api/venv/bin/pip3 install -r ~/%%DIRECTORY_NAME%%-staging/api/requirements.txt
            echo ${{ secrets.SUDO_PASSWORD }} | sudo -S systemctl restart %%SERVICE_NAME%%-staging.service

  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check our runner's IP
        run: curl ifconfig.me

      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Get version number
        run: echo "TAG=$(cat $GITHUB_WORKSPACE/version.py | grep -oP '[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}')" >> $GITHUB_ENV

      - name: docker login
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_USER }}/%%APP_ID%%-frontend:${{ env.TAG }}-staging -f ./frontend/Dockerfile-staging ./frontend

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_USER }}/%%APP_ID%%-frontend:${{ env.TAG }}-staging

      - name: restarting docker container
        uses: appleboy/ssh-action@master
        with:
          host: %%SERVER_IP%%
          username: steven
          key: ${{ secrets.SSH_KEY }}
          # passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          port: 22
          script: |
            PATH=~/.local/bin:$PATH
            slg-restart-docker-container ${{ secrets.SUDO_PASSWORD }} slgotting/%%APP_ID%%-frontend staging-%%APP_ID%%-frontend ${{ env.TAG }}-staging -p %%STAGING_FRONTEND_PORT%% --run_args "-e MODE=staging"
